#! /bin/sh

# clean up bspc
bspc rule -r "*"

echo "=> [$(date --rfc-3339=ns)] Setting up session and bspwm" >&2

# Systemd --user does not properly support this usecase so I start and kill
# services and apps manually here.

# starts an "app" if it is not already running
start_app() {
  echo "=> Starting app $@"
  pgrep "$1" || "$@" &
}

# kills (if it is already running) and starts a "service"
# note this will kill all instance of the running "service"
start_service() {
  echo "=> Starting service $@"
  killall "$1"
  "$@" &
}

#
# services and apps are started (roughly) in order of importance
#

# keyboard shortcut daemon
export SXHKD_SHELL=/usr/bin/bash
SXHKD_FIFO=/run/user/$UID/sxhkd.fifo
mkfifo $SXHKD_FIFO
start_service sxhkd -s $SXHKD_FIFO

# bars are handled by an extra script because the setup is a little more complex
~/.config/bspwm/bars.sh &

# autolock setup
# locks after 5min, dims screen 30sec before that and suspends 1h after lock
rm ~/.xidlehook.socket
start_service xidlehook \
  --not-when-fullscreen \
  --socket ~/.xidlehook.socket \
  --timer 270 \
    'for m in $(xrandr | grep -E " connected (primary )?[1-9]+" | sed -e "s/\([A-Z0-9]\+\) connected.*/\1/"); do xrandr --output $m --brightness 0.5; done' \
    'for m in $(xrandr | grep -E " connected (primary )?[1-9]+" | sed -e "s/\([A-Z0-9]\+\) connected.*/\1/"); do xrandr --output $m --brightness 1; done' \
  --timer 30 \
    'for m in $(xrandr | grep -E " connected (primary )?[1-9]+" | sed -e "s/\([A-Z0-9]\+\) connected.*/\1/"); do xrandr --output $m --brightness 1; done; ~/.config/bspwm/run-locker.sh' \
    '' \
  --timer 3600 \
    'systemctl suspend' \
    ''

# compositor
start_service picom
# notifications
start_service dunst

# set background
feh --no-fehbg --bg-fill ~/.config/bspwm/wallpaper.jpg &

# start other apps
start_app syncthing-gtk
start_app nm-applet --sm-disable

# fix gnome apps and service
# TODO not sure if needed with bspwn
dbus-update-activation-environment \
  --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY &


# TODO this is not ideal because it immediately calls the script
start_service mons -a -x ~/.config/bspwm/handle-monitor-change.sh

#
# bspwm setup
#

bspc monitor eDP1 -d 1 2 3 4 5 6
bspc monitor HDMI2 -d 7 8 9 0

# bspc config remove_unplugged_monitors true
# bspc config remove_disabled_monitors true

bspc config border_width         2
bspc config window_gap           0

bspc config normal_border_color '#282828'
bspc config active_border_color '#282828'
bspc config focused_border_color '#ab4642'

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config automatic_scheme longest_side

bspc config focus_follows_pointer  false
bspc config click_to_focus         button1
bspc config honor_size_hints       true
bspc config ignore_ewmh_focus      false
bspc config ignore_ewmh_fullscreen none
bspc config ignore_ewmh_struts     false

# TODO some of these do not work
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^1'
bspc rule -a Thunderbird desktop='^10'
bspc rule -a Spotify desktop='^9'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

